In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import norm
from scipy import stats
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [ ]:
data = pd.read_csv('mpg_data.csv')

In [ ]:
data.head()

mpg  cylinders  displacement  ...  model year  origin                   car name
0  18.0          8         307.0  ...          70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...          70       1          buick skylark 320
2  18.0          8         318.0  ...          70       1         plymouth satellite
3  16.0          8         304.0  ...          70       1              amc rebel sst
4  17.0          8         302.0  ...          70       1                ford torino

[5 rows x 9 columns]

In [ ]:
data.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [ ]:
data.isnull().any()

mpg             False
cylinders       False
displacement    False
horsepower       True
weight          False
acceleration    False
model year      False
origin          False
car name        False
dtype: bool

In [ ]:
data['horsepower'].fillna((data['horsepower'].mean()), inplace=True)

In [ ]:
data.describe()

mpg   cylinders  ...  model year      origin
count  398.000000  398.000000  ...  398.000000  398.000000
mean    23.514573    5.454774  ...   76.010050    1.572864
std      7.815984    1.701004  ...    3.697627    0.802055
min      9.000000    3.000000  ...   70.000000    1.000000
25%     17.500000    4.000000  ...   73.000000    1.000000
50%     23.000000    4.000000  ...   76.000000    1.000000
75%     29.000000    8.000000  ...   79.000000    2.000000
max     46.600000    8.000000  ...   82.000000    3.000000

[8 rows x 8 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
factors = ['cylinders','displacement','horsepower','acceleration','weight','origin','model year']
X = pd.DataFrame(data[factors].copy())
y = data['mpg'].copy()

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size = 0.33,random_state=324)
X_train.shape[0] == y_train.shape[0]

True

In [ ]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [ ]:
X_train_scaled = scaler.transform(X_train)

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(X_train_scaled,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
from pickle import dump

In [ ]:
dump(model, open('model.pkl', 'wb'))
dump(scaler, open('scaler.pkl', 'wb'))

In [ ]:
from pickle import load

In [ ]:
model = load(open('model.pkl', 'rb'))
# load the scaler
scaler = load(open('scaler.pkl', 'rb'))

In [ ]:
X_test_scaled = scaler.transform(X_test)

In [ ]:
X_test

cylinders  displacement  horsepower  ...  weight  origin  model year
299          4         141.0        71.0  ...    3190       2          79
73           8         307.0       130.0  ...    4098       1          72
155          6         250.0        72.0  ...    3158       1          75
164          6         231.0       110.0  ...    3039       1          75
85           8         350.0       175.0  ...    4100       1          73
..         ...           ...         ...  ...     ...     ...         ...
103          8         400.0       150.0  ...    4997       1          73
283          6         232.0        90.0  ...    3265       1          79
74           8         302.0       140.0  ...    4294       1          72
59           4          97.0        54.0  ...    2254       2          72
145          4          83.0        61.0  ...    2003       3          74

[132 rows x 7 columns]

In [ ]:
yhat = model.predict(X_test_scaled)
yhat

array([25.80062558, 12.5951797 , 22.97728027, 21.89444048, 13.1669414 ,
       32.45238551, 13.50991598,  8.88690757, 10.2865107 , 18.98150144,
       28.44956837, 27.78851612, 20.81273017, 22.84844919, 11.6363639 ,
       27.07250556, 34.78722995, 29.96917443, 23.7155859 , 22.11071662,
       22.04116578, 21.24174918, 28.95464125, 31.86526355,  6.04799024,
        8.25085687, 31.44146104, 15.60212031,  9.67352462, 26.39410179,
       14.10632933, 25.21341076, 31.31580079, 16.50301389, 21.04591782,
       32.07042284, 22.36356233, 25.34462989, 18.73258154, 30.77170994,
       22.51998416, 21.08575631, 17.68921667, 30.50730495,  5.1199258 ,
       24.81060424, 15.24145069, 10.54357534, 34.50320733, 28.63604471,
       20.08119019,  7.03188344, 20.30346514, 29.66061095, 30.11557622,
       25.19658046, 26.55841371, 33.35738291,  8.27711951, 25.56535155,
       32.37047385, 33.83440046, 32.743785  , 29.50695203, 15.21268305,
       22.95975948, 24.94918489, 24.15275574, 33.204147  , 28.42

In [ ]:
mean_squared_error(y_test,yhat)

11.105454122887837

In [ ]:
val = {'cylinders' : 4,
       'displacement' : 141,
       'horsepower' : 71,
       'acceleration' : 24.8,
       'weight' : 3190,
       'origin' : 2,
       'model year' : 79        
}

In [ ]:
d = pd.DataFrame(val, columns = ['cylinders',	'displacement',	'horsepower',	'acceleration', 'weight',	'origin',	'model year'],index=[0])
d

cylinders  displacement  horsepower  ...  weight  origin  model year
0          4           141          71  ...    3190       2          79

[1 rows x 7 columns]

In [ ]:
d_scaled = scaler.transform(d)

In [ ]:
model.predict(d_scaled)

array([25.80062558])

In [ ]:
d_scaled

array([[-0.82049435, -0.46098959, -0.87881366,  3.5061541 ,  0.33221903,
         0.47616332,  0.76139117]])